# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Electron Application

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Build CSS
      run: npm run build-css
   # - name: Build for MacOS
   #   run: npm run build-mac
    - name: Install Wine64
      run: sudo apt-get install wine64
    - name: Build for Windows x64
      run: npm run build-win
   # - name: Build for Linux
   #   run: npm run build-linux
      env:
        testing: yes
    - name: Sort Build Files
      # continue-on-error: true
      run: |
          shopt -s extglob
          wget https://raw.githubusercontent.com/Trail-Blaze/cdn/main/buildCheck_new.sh
          sudo chmod +x buildCheck_new.sh
          ./buildCheck_new.sh
      shell: bash         
    - name: Upload Windows Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
          # Artifact name
          name: build_win-latest.tar.gz
          # A file, directory or wildcard pattern that describes what to upload
          path: build_win-latest.tar.gz
          warn: Output a warning but do not fail the action
          if-no-files-found: warn
          # Duration after which artifact will expire in days. 0 means using default retention.
          retention-days: 31
